### Try to register user (Hashed password: kaszanka)
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "firstName": "Piotr",
  "lastName": "Skowyrski",
  "password": "kaszanka",
  "mail": "michal.maziarz12@gmail.com",
  "phone": "997 998 112"
}

### Then, after mail confirmation try to log in
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "mail": "admin",
  "password": "kaszanka"
}

> {% client.global.set("auth_token", response.body.token); %}

### TEST
POST http://localhost:8080/api/room/add
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "resortId": 10,
  "name": "XD",
  "pearsonCount": 10,
  "standard": 3
}

### Find cities
GET http://localhost:8080/public/api/location/countries?name=P

### Add city
POST http://localhost:8080/api/location/addCity
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Mirały",
  "country": "Polska",
  "latitude": "23"
}

### Add resort
POST http://localhost:8080/api/resort/add
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Super wycieczka",
  "description": "Przeżyj to sam",
  "address": {
    "buildingNumber": "21",
    "houseNumber": "37",
    "street": "Żarska",
    "city": {
      "name": "Compton",
      "country": "Pologne"
    }
  },
  "rooms": [{
    "standard": 3,
    "name": "Squot",
    "personCount": 29
  }]
}

### Get incoming tours
POST http://localhost:8080/public/api/tours/incoming
Content-Type: application/json

{
  "resortId": 1,
  "page": 0
}

### Get done tours
GET http://localhost:8080/api/tours/done?resortId=2&page=0
Authorization: Bearer {{auth_token}}

### Get current tours
GET http://localhost:8080/api/tours/ongoing?resortId=4&departureDate=2024-01-01&page=0
Authorization: Bearer {{auth_token}}

### Popularity report
GET http://localhost:8080/api/resort/popularityReport?startDate=2023-01-01&endDate=2024-10-10&page=1&size=2
Authorization: Bearer {{auth_token}}

### Add tour
POST http://localhost:8080/api/tours/add
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "n",
  "description": "d",
  "departureDate": "2024-06-06",
  "returnDate": "2024-07-01",
  "price": 2137.21,
  "resortId": 5,
  "roomIds": [17],
  "facilities": {
    "airConditioning": true,
    "allTimeReception": true,
    "bar": true,
    "food": true,
    "freeParking": true,
    "gym": true,
    "restaurant": true,
    "roomService": true,
    "swimmingPool": true,
    "wifi": true
  }
}

### Get available rooms
GET http://localhost:8080/public/api/tour/availableRooms?tourId=5

### Sign contract
POST http://localhost:8080/api/contracts/add
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "tourId": 5,
  "roomIds": [17]
}

### Get opinions
GET http://localhost:8080/public/api/opinions?resortId=1&page=0