package pl.tourpol.backend.security.exception;

public enum RequestErrorMessage {
    MAIL_ALREADY_EXISTS,
    RESORT_NOT_EXISTS,
    ROOM_NOT_EXISTS,
    ROOM_BUSY,
    TOUR_NOT_EXISTS,
    ROOM_ADD_INVALID_PERSON_COUNT,
    ROOM_ADD_INVALID_STANDARD,
    INVALID_NAME,
    INVALID_DATE,
    INVALID_PRICE,
    INVALID_DESCRIPTION,
    CONTRACT_NOT_EXISTS
}
