version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: tourpol
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./scripts/DDL:/DDL
      - ./scripts/DML:/DML
    ports:
      - "5432:5432"